### PR TITLE
Changes # 11/7/24

### PR DESCRIPTION
**Pull request by Sunny0734**
Added a back-to-top button on both mobile view and laptop view. Adjusted the hamburger on mobile view and formatted all the code.

### CODE REVIEW

**Comment by bboonstra** [comment]
Resolve your conflicts

**Comment by Sunny0734** [comment]
What should i do? What do you mean by conflicts bro?

**Comment by bboonstra** [comment]
Screenshot 2024-11-09 at 7 46 56 PM

**Comment by bboonstra** [comment]
Are you unable to see this? You can also try

Step 1: Clone the repository or update your local repository with the latest changes.

git pull origin main
Step 2: Switch to the head branch of the pull request.

git checkout 'changes-#-11/7/24'
Step 3: Merge the base branch into the head branch.

git merge main
Step 4: Fix the conflicts and commit the result.

See [Resolving a merge conflict using the command line](https://docs.github.com/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) for step-by-step instructions on resolving merge conflicts.
Step 5: Push the changes.

git push -u origin 'changes-#-11/7/24'

**Review by bboonstra — APPROVED** [review]
Baller

**Pull request merged**
